# Generated by Django 2.2.4 on 2019-10-06 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_make', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_rating', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_and_time', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True)),
                ('machinemake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineMake', to='machine.MachineMake')),
                ('machinename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineName', to='machine.MachineName')),
                ('machinerating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineRating', to='machine.MachineRating')),
                ('machinetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineType', to='machine.MachineType')),
            ],
        ),
    ]
