# Generated by Django 2.2.4 on 2019-10-08 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_details', '0002_customerdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_no', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('date_of_complaint', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_of_completion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('problem', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('rectification', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cost', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('payment_status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer_details.ContactPerson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
