# Generated by Django 2.2.4 on 2019-10-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='date_of_complaint',
            field=models.DateField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='date_of_completion',
            field=models.DateField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
