# Generated by Django 2.2.4 on 2019-10-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('companyAddress', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactPersonName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('contactPersonMobileNumber', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('contactPersonEmailId', models.EmailField(blank=True, default=None, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyName', to='customer_details.Company')),
            ],
        ),
    ]
